
/* Screens */
export const SCREEN_CONVERSATION = 'SCREEN_CONVERSATION';
export const SCREEN_CONVERSATION_LIST= 'SCREEN_CONVERSATION_LIST';
export const SCREEN_ME = 'SCREEN_ME';
export const SCREEN_TODAY = 'SCREEN_TODAY';
export const SCREEN_PROFILE = 'SCREEN_PROFILE';
export const SCREEN_HISTORY = 'SCREEN_HISTORY';
export const SCREEN_EDIT_PROFILE = 'SCREEN_EDIT_PROFILE';

export const TAB_SCREEN_CONTAINER= 'TAB_SCREEN_CONTAINER';
export const CURRENT_SCREEN = 'CURRENT_SCREEN';

/* Actions */
export const SWITCH_BASE_TAB = 'SWITCH_BASE_TAB';
