// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//



public enum R {
    public enum ConversationAssets : String {
        /// empty-profile-pic
        case emptyProfilePic = "empty-profile-pic"
        /// ic-back-arrow
        case icBackArrow = "ic-back-arrow"
        /// ic-down-chevron-small
        case icDownChevronSmall = "ic-down-chevron-small"
        /// ic-more
        case icMore = "ic-more"
        /// ic-play-medium
        case icPlayMedium = "ic-play-medium"
        /// ic-speaker
        case icSpeaker = "ic-speaker"
        /// ic-speaker-muted
        case icSpeakerMuted = "ic-speaker-muted"
        /// sample-photo
        case samplePhoto = "sample-photo"
    }
    public enum Fonts : String {
        /// Cabin-Bold
        case cabinBold = "Cabin-Bold"
        /// Cabin-BoldItalic
        case cabinBoldItalic = "Cabin-BoldItalic"
        /// Cabin-Italic
        case cabinItalic = "Cabin-Italic"
        /// Cabin-Medium
        case cabinMedium = "Cabin-Medium"
        /// Cabin-MediumItalic
        case cabinMediumItalic = "Cabin-MediumItalic"
        /// Cabin-Regular
        case cabinRegular = "Cabin-Regular"
    }
    public enum Strings : String {
        /// Block %@
        case moreSheetBlock = "MoreSheetBlock"
        /// Cancel
        case moreSheetCancel = "MoreSheetCancel"
        /// Report %@
        case moreSheetReport = "MoreSheetReport"
        /// We send your location to your connections only when you explicitly request it.
        case nsLocationWhenInUseUsageDescription = "NSLocationWhenInUseUsageDescription"
        /// Cancel
        case reportAlertCancel = "ReportAlertCancel"
        /// Confirm
        case reportAlertConfirm = "ReportAlertConfirm"
        /// Why did you report this user?
        case reportAlertMessage = "ReportAlertMessage"
        /// Thank you for your feedback
        case reportAlertTitle = "ReportAlertTitle"
        /// View Profile
        case viewProfile = "ViewProfile"
    }
    public enum TaylrAssets : String {
        /// AppIcon
        case app = "AppIcon"
        /// Logo
        case logo = "Logo"
    }
}
