platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

# Core
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # Add any other subspecs you want to use in your project
]
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
pod 'LayerKit', '~> 0.17'
pod 'Atlas', '~> 1.0.15'
pod 'SCRecorder', '2.5.3' # ScaleAspectFill bug
# pod 'NKRecorder', :path => '../../video-maker'
pod 'NKRecorder', :git => 'git@github.com:s10tv/video-maker.git'

# Utils
pod 'SwiftyUserDefaults', '~> 2.0'
pod 'SimpleKeychain', '~> 0.4'
pod 'DTFoundation/DTASN1', '~> 1.7'
pod 'SDWebImage', '~> 3.7'

# UI
pod 'Cartography', '~> 0.6'
pod 'EDColor', '~> 1.0'
pod 'SwipeView', '~> 1.3'
pod 'AMPopTip', '~> 0.9'
pod 'SVProgressHUD', '~> 2.0-beta'

# SDKs
pod 'FBSDKLoginKit', '~> 4.8'
pod 'Fabric', '~> 1.6'
pod 'TwitterCore', '~> 1.13'
pod 'Digits', '~> 1.13'
pod 'Crashlytics', '~> 3.4'
pod 'OneSignal', '~> 1.10'

# Logging
pod 'CocoaLumberjack/Swift', '~> 2.2'
pod 'Ouralabs', '~> 2.6'
pod 'NSLogger', '~> 1.5', :configuration => ['Debug']

# Analytics
pod 'Mixpanel', '~> 2.9'
pod 'Amplitude-iOS', '~> 3.2'
pod 'AnalyticsSwift', '~> 0.2' # SegmentIO
pod 'Intercom', '~> 2.3'
pod 'Branch', '~> 0.11'
# Disabling UXCam for dev builds until motion detection interference is fixed
pod 'UXCam', '~> 2.4' #, :configuration => ['Release']

# Debugging
pod 'Reveal-iOS-SDK', '~> 1.6', :configuration => ['Debug']

# To Be Deprecated
pod 'DateTools', '~> 1.7'
pod 'FormatterKit/TimeIntervalFormatter', '~> 1.8'

post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"
    installer.pods_project.targets.each do |target|
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        original_version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
        changed_version = original_version[/(\d+\.){1,2}(\d+)?/]
        unless original_version == changed_version
            puts "Fix version of Pod #{target}: #{original_version} => #{changed_version}"
            `#{plist_buddy} -c "Set CFBundleShortVersionString #{changed_version}" "Pods/Target Support Files/#{target}/Info.plist"`
        end
    end
end