platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

# Core
pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # Add any other subspecs you want to use in your project
]
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
pod 'LayerKit', '~> 0.17'
pod 'Atlas', '~> 1.0.13'
pod 'SCRecorder', '2.5.3' # ScaleAspectFill bug
# pod 'NKRecorder', :path => '../video-maker'
pod 'NKRecorder', :git => 'git@github.com:s10tv/video-maker.git'

# Utils
pod 'Alamofire', '~> 3.1'
pod 'SimpleKeychain', '~> 0.4'
pod 'DTFoundation/DTASN1', '~> 1.7'
pod 'SDWebImage', '~> 3.7'

# UI
pod 'Cartography', '~> 0.6'
pod 'EDColor', '~> 1.0'
pod 'SwipeView', '~> 1.3'
pod 'AMPopTip', '~> 0.9'

# SDKs
pod 'FBSDKLoginKit', '~> 4.8'
pod 'Fabric', '~> 1.5'
pod 'TwitterCore', '~> 1.11'
pod 'Digits', '~> 1.11'

# Logging & analytics
pod 'Crashlytics', '~> 3.3'
pod 'Ouralabs', '~> 2.6'

pod 'AnalyticsSwift', '~> 0.2'
pod 'Mixpanel', '~> 2.9'
pod 'Amplitude-iOS', '~> 3.1'
pod 'UXCam', '~> 2.3'

# Debug only
pod 'NSLogger', '~> 1.5', :configuration => ['Debug']
pod 'Reveal-iOS-SDK', '~> 1.5', :configuration => ['Debug']

# To Be Deprecated
pod 'DateTools', '~> 1.7'
pod 'FormatterKit/TimeIntervalFormatter', '~> 1.8'
pod 'PKHUD', :git => 'https://github.com/tonyxiao/PKHUD' # Fork is needed to work around xcasset compilation issue inside pod

post_install do |installer|
    app_plist = "Taylr/Taylr-Info.plist"
    plist_buddy = "/usr/libexec/PlistBuddy"
    version = `#{plist_buddy} -c "Print CFBundleShortVersionString" #{app_plist}`.strip
    puts "Updating CocoaPods' version numbers to #{version}"

    installer.pods_project.targets.each do |target|
        `#{plist_buddy} -c "Set CFBundleShortVersionString #{version}" "Pods/Target Support Files/#{target}/Info.plist"`
    end
end
