// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import <Foundation/Foundation.h>

extern const struct R {
    struct ImagesAssets {
        /// AppIcon
        __unsafe_unretained NSString *app;
        /// AppIconBeta
        __unsafe_unretained NSString *appBeta;
        /// AppIconDev
        __unsafe_unretained NSString *appDev;
        /// background-sea-short
        __unsafe_unretained NSString *backgroundSeaShort;
        /// dock-separator
        __unsafe_unretained NSString *dockSeparator;
        /// game-bucket-keep
        __unsafe_unretained NSString *gameBucketKeep;
        /// game-bucket-marry
        __unsafe_unretained NSString *gameBucketMarry;
        /// game-bucket-skip
        __unsafe_unretained NSString *gameBucketSkip;
        /// game-empty-share-facebook
        __unsafe_unretained NSString *gameEmptyShareFacebook;
        /// game-empty-share-sms
        __unsafe_unretained NSString *gameEmptyShareSms;
        /// game-empty-share-twitter
        __unsafe_unretained NSString *gameEmptyShareTwitter;
        /// game-progressIndicator-1
        __unsafe_unretained NSString *gameProgressIndicator1;
        /// game-progressIndicator-2
        __unsafe_unretained NSString *gameProgressIndicator2;
        /// game-progressIndicator-3
        __unsafe_unretained NSString *gameProgressIndicator3;
        /// girl-placeholder
        __unsafe_unretained NSString *girlPlaceholder;
        /// guy-placeholder
        __unsafe_unretained NSString *guyPlaceholder;
        /// ic_remove_photo
        __unsafe_unretained NSString *icRemovePhoto;
        /// Ketch
        __unsafe_unretained NSString *ketch;
        /// profile-about-me-divider
        __unsafe_unretained NSString *profileAboutMeDivider;
        /// settings-icon-age
        __unsafe_unretained NSString *settingsAge;
        /// settings-icon-briefcase
        __unsafe_unretained NSString *settingsBriefcase;
        /// settings-icon-heightArrow
        __unsafe_unretained NSString *settingsHeightArrow;
        /// settings-icon-location
        __unsafe_unretained NSString *settingsLocation;
        /// settings-icon-mortarBoard
        __unsafe_unretained NSString *settingsMortarBoard;
        /// settings-icon-notepad
        __unsafe_unretained NSString *settingsNotepad;
    } ImagesAssets;
    struct JSQMessagesAssets {
        /// Images/bubble_min.png
        __unsafe_unretained NSString *sBubbleMin;
        /// Images/bubble_min@3x.png
        __unsafe_unretained NSString *sBubbleMin3x;
        /// Images/bubble_min_tailless.png
        __unsafe_unretained NSString *sBubbleMinTailless;
        /// Images/bubble_min_tailless@3x.png
        __unsafe_unretained NSString *sBubbleMinTailless3x;
        /// Images/bubble_regular.png
        __unsafe_unretained NSString *sBubbleRegular;
        /// Images/bubble_regular@3x.png
        __unsafe_unretained NSString *sBubbleRegular3x;
        /// Images/bubble_stroked.png
        __unsafe_unretained NSString *sBubbleStroked;
        /// Images/bubble_stroked@3x.png
        __unsafe_unretained NSString *sBubbleStroked3x;
        /// Images/bubble_stroked_tailless.png
        __unsafe_unretained NSString *sBubbleStrokedTailless;
        /// Images/bubble_stroked_tailless@3x.png
        __unsafe_unretained NSString *sBubbleStrokedTailless3x;
        /// Images/bubble_tailless.png
        __unsafe_unretained NSString *sBubbleTailless;
        /// Images/bubble_tailless@3x.png
        __unsafe_unretained NSString *sBubbleTailless3x;
        /// Images/clip.png
        __unsafe_unretained NSString *sClip;
        /// Images/clip@3x.png
        __unsafe_unretained NSString *sClip3x;
        /// Images/play.png
        __unsafe_unretained NSString *sPlay;
        /// Images/play@3x.png
        __unsafe_unretained NSString *sPlay3x;
        /// Images/typing.png
        __unsafe_unretained NSString *sTyping;
        /// Images/typing@3x.png
        __unsafe_unretained NSString *sTyping3x;
    } JSQMessagesAssets;
    struct Strings {
        /// DECIDE WHAT YOU PREFER
        __unsafe_unretained NSString *dragMatchsToChoices;
        /// It's a Ketch!
        __unsafe_unretained NSString *itsAKetch;
        /// SAY YES NOW
        __unsafe_unretained NSString *marryPrompt;
        /// %@ likes you! Your dreamboat will sail off in three days. Get on it before %@ disappears for good!
        __unsafe_unretained NSString *singleMatchPrompt;
        /// SAY NO POLITELY
        __unsafe_unretained NSString *skipPrompt;
        /// SEE AGAIN LATER
        __unsafe_unretained NSString *snoozePrompt;
        /// AND YOU’LL HAVE THREE CHOICES
        __unsafe_unretained NSString *threeChoicesPrompt;
        /// YOU’LL SEE THREE POTENTIAL MATCHES
        __unsafe_unretained NSString *threeMatchesPrompt;
    } Strings;
} R;
