// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import <Foundation/Foundation.h>

extern const struct R {
    struct ImagesAssets {
        /// AppIcon
        __unsafe_unretained NSString *app;
        /// AppIconBeta
        __unsafe_unretained NSString *appBeta;
        /// AppIconDev
        __unsafe_unretained NSString *appDev;
        /// background-sea-short
        __unsafe_unretained NSString *backgroundSeaShort;
        /// BGWave
        __unsafe_unretained NSString *bgWave;
        /// bottom-sea
        __unsafe_unretained NSString *bottomSea;
        /// dock-separator
        __unsafe_unretained NSString *dockSeparator;
        /// game-arrow-down
        __unsafe_unretained NSString *gameArrowDown;
        /// game-bucket-anchor-white
        __unsafe_unretained NSString *gameBucketAnchorWhite;
        /// game-bucket-keep
        __unsafe_unretained NSString *gameBucketKeep;
        /// game-bucket-keep-white
        __unsafe_unretained NSString *gameBucketKeepWhite;
        /// game-bucket-knot-white
        __unsafe_unretained NSString *gameBucketKnotWhite;
        /// game-bucket-marry
        __unsafe_unretained NSString *gameBucketMarry;
        /// game-bucket-skip
        __unsafe_unretained NSString *gameBucketSkip;
        /// game-empty-share-facebook
        __unsafe_unretained NSString *gameEmptyShareFacebook;
        /// game-empty-share-sms
        __unsafe_unretained NSString *gameEmptyShareSms;
        /// game-empty-share-twitter
        __unsafe_unretained NSString *gameEmptyShareTwitter;
        /// game-progressIndicator-1
        __unsafe_unretained NSString *gameProgressIndicator1;
        /// game-progressIndicator-2
        __unsafe_unretained NSString *gameProgressIndicator2;
        /// game-progressIndicator-3
        __unsafe_unretained NSString *gameProgressIndicator3;
        /// girl-placeholder
        __unsafe_unretained NSString *girlPlaceholder;
        /// guy-placeholder
        __unsafe_unretained NSString *guyPlaceholder;
        /// Header
        __unsafe_unretained NSString *header;
        /// ic_home
        __unsafe_unretained NSString *icHome;
        /// ic_remove_photo
        __unsafe_unretained NSString *icRemovePhoto;
        /// ic_school
        __unsafe_unretained NSString *icSchool;
        /// ic_work
        __unsafe_unretained NSString *icWork;
        /// keepText
        __unsafe_unretained NSString *keepText;
        /// Ketch
        __unsafe_unretained NSString *ketch;
        /// launch-logo
        __unsafe_unretained NSString *launchLogo;
        /// marryText
        __unsafe_unretained NSString *marryText;
        /// settings-icon-age
        __unsafe_unretained NSString *settingsAge;
        /// settings-icon-briefcase
        __unsafe_unretained NSString *settingsBriefcase;
        /// settings-icon-heightArrow
        __unsafe_unretained NSString *settingsHeightArrow;
        /// settings-icon-mortarBoard
        __unsafe_unretained NSString *settingsMortarBoard;
        /// settings-icon-notepad
        __unsafe_unretained NSString *settingsNotepad;
        /// skipText
        __unsafe_unretained NSString *skipText;
        /// welcome-user-1
        __unsafe_unretained NSString *welcomeUser1;
        /// welcome-user-2
        __unsafe_unretained NSString *welcomeUser2;
        /// welcome-user-3
        __unsafe_unretained NSString *welcomeUser3;
    } ImagesAssets;
    struct JSQMessagesAssets {
        /// Images/bubble_min.png
        __unsafe_unretained NSString *sBubbleMin;
        /// Images/bubble_min@3x.png
        __unsafe_unretained NSString *sBubbleMin3x;
        /// Images/bubble_min_tailless.png
        __unsafe_unretained NSString *sBubbleMinTailless;
        /// Images/bubble_min_tailless@3x.png
        __unsafe_unretained NSString *sBubbleMinTailless3x;
        /// Images/bubble_regular.png
        __unsafe_unretained NSString *sBubbleRegular;
        /// Images/bubble_regular@3x.png
        __unsafe_unretained NSString *sBubbleRegular3x;
        /// Images/bubble_stroked.png
        __unsafe_unretained NSString *sBubbleStroked;
        /// Images/bubble_stroked@3x.png
        __unsafe_unretained NSString *sBubbleStroked3x;
        /// Images/bubble_stroked_tailless.png
        __unsafe_unretained NSString *sBubbleStrokedTailless;
        /// Images/bubble_stroked_tailless@3x.png
        __unsafe_unretained NSString *sBubbleStrokedTailless3x;
        /// Images/bubble_tailless.png
        __unsafe_unretained NSString *sBubbleTailless;
        /// Images/bubble_tailless@3x.png
        __unsafe_unretained NSString *sBubbleTailless3x;
        /// Images/clip.png
        __unsafe_unretained NSString *sClip;
        /// Images/clip@3x.png
        __unsafe_unretained NSString *sClip3x;
        /// Images/play.png
        __unsafe_unretained NSString *sPlay;
        /// Images/play@3x.png
        __unsafe_unretained NSString *sPlay3x;
        /// Images/typing.png
        __unsafe_unretained NSString *sTyping;
        /// Images/typing@3x.png
        __unsafe_unretained NSString *sTyping3x;
    } JSQMessagesAssets;
    struct Strings {
        /// Both %@ and %@ were charmed by you. Why not get in touch and see how things go?
        __unsafe_unretained NSString *doubleMatchPrompt;
        /// It's a Ketch!
        __unsafe_unretained NSString *itsAKetch;
        /// Lucky you!
        __unsafe_unretained NSString *luckyYou;
        /// It seems that %@ also thought you were pretty darn cute. Why not chat and see how things go?
        __unsafe_unretained NSString *singleMatchPrompt;
    } Strings;
} R;
