// generated by xcres
//
// DO NOT EDIT. This file is machine-generated and constantly overwritten.
// See https://github.com/mrackwitz/xcres for more info.
//


#import "R.h"

const struct R R = {
    .ImagesAssets = {
        .app = @"AppIcon",
        .appBeta = @"AppIconBeta",
        .appDev = @"AppIconDev",
        .backgroundSeaShort = @"background-sea-short",
        .bgWave = @"BGWave",
        .dockSeparator = @"dock-separator",
        .gameArrowDown = @"game-arrow-down",
        .gameBucketKeep = @"game-bucket-keep",
        .gameBucketMarry = @"game-bucket-marry",
        .gameBucketSkip = @"game-bucket-skip",
        .gameEmptyShareFacebook = @"game-empty-share-facebook",
        .gameEmptyShareSms = @"game-empty-share-sms",
        .gameEmptyShareTwitter = @"game-empty-share-twitter",
        .gameProgressIndicator1 = @"game-progressIndicator-1",
        .gameProgressIndicator2 = @"game-progressIndicator-2",
        .gameProgressIndicator3 = @"game-progressIndicator-3",
        .girlPlaceholder = @"girl-placeholder",
        .guyPlaceholder = @"guy-placeholder",
        .icHome = @"ic_home",
        .icRemovePhoto = @"ic_remove_photo",
        .icSchool = @"ic_school",
        .icWork = @"ic_work",
        .ketch = @"Ketch",
        .launchLogo = @"launch-logo",
        .settingsAge = @"settings-icon-age",
        .settingsBriefcase = @"settings-icon-briefcase",
        .settingsHeightArrow = @"settings-icon-heightArrow",
        .settingsMortarBoard = @"settings-icon-mortarBoard",
        .settingsNotepad = @"settings-icon-notepad",
    },
    .JSQMessagesAssets = {
        .sBubbleMin = @"Images/bubble_min.png",
        .sBubbleMin3x = @"Images/bubble_min@3x.png",
        .sBubbleMinTailless = @"Images/bubble_min_tailless.png",
        .sBubbleMinTailless3x = @"Images/bubble_min_tailless@3x.png",
        .sBubbleRegular = @"Images/bubble_regular.png",
        .sBubbleRegular3x = @"Images/bubble_regular@3x.png",
        .sBubbleStroked = @"Images/bubble_stroked.png",
        .sBubbleStroked3x = @"Images/bubble_stroked@3x.png",
        .sBubbleStrokedTailless = @"Images/bubble_stroked_tailless.png",
        .sBubbleStrokedTailless3x = @"Images/bubble_stroked_tailless@3x.png",
        .sBubbleTailless = @"Images/bubble_tailless.png",
        .sBubbleTailless3x = @"Images/bubble_tailless@3x.png",
        .sClip = @"Images/clip.png",
        .sClip3x = @"Images/clip@3x.png",
        .sPlay = @"Images/play.png",
        .sPlay3x = @"Images/play@3x.png",
        .sTyping = @"Images/typing.png",
        .sTyping3x = @"Images/typing@3x.png",
    },
    .Strings = {
        .doubleMatchPrompt = @"DoubleMatchPrompt",
        .dragMatchsToChoices = @"DragMatchsToChoices",
        .itsAKetch = @"It's a Ketch!",
        .luckyYou = @"Lucky you!",
        .marryPrompt = @"MarryPrompt",
        .singleMatchPrompt = @"SingleMatchPrompt",
        .skipPrompt = @"SkipPrompt",
        .snoozePrompt = @"SnoozePrompt",
        .threeChoicesPrompt = @"ThreeChoicesPrompt",
        .threeMatchesPrompt = @"ThreeMatchesPrompt",
    },
};
