//
//  StyleKit.swift
//  Ketch
//
//  Created by Alex Ketch on 3/3/15.
//  Copyright (c) 2015 Milasya Inc.. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var teal: UIColor = UIColor(red: 0.136, green: 0.587, blue: 0.580, alpha: 1.000)
        static var navy: UIColor = UIColor(red: 0.051, green: 0.392, blue: 0.537, alpha: 1.000)
        static var coral: UIColor = UIColor(red: 0.945, green: 0.400, blue: 0.227, alpha: 1.000)
        static var white: UIColor = UIColor(red: 0.941, green: 0.980, blue: 0.969, alpha: 1.000)
        static var brandBlue: UIColor = UIColor(red: 0.055, green: 0.894, blue: 0.941, alpha: 1.000)
        static var brandAlt: UIColor = UIColor(red: 0.263, green: 0.871, blue: 0.863, alpha: 1.000)
        static var gradientWaterColor: UIColor = UIColor(red: 0.549, green: 0.976, blue: 1.000, alpha: 1.000)
        static var gradientSandColor: UIColor = UIColor(red: 0.882, green: 0.871, blue: 0.788, alpha: 1.000)
        static var gradientSandColor2: UIColor = UIColor(red: 0.941, green: 0.980, blue: 0.969, alpha: 1.000)
        static var pureWhite: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static var darkWhite: UIColor = StyleKit.white.colorWithBrightness(0.9)
        static var gradientBlue: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [StyleKit.brandBlue.CGColor, StyleKit.brandAlt.CGColor], [0, 1])
        static var gradientWater: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [StyleKit.gradientWaterColor.CGColor, StyleKit.brandBlue.CGColor, StyleKit.brandAlt.CGColor], [0, 0.19, 1])
        static var gradientSand: CGGradient = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [StyleKit.gradientSandColor.CGColor, StyleKit.gradientSandColor2.CGColor], [0, 1])
    }

    //// Colors

    public class var teal: UIColor { return Cache.teal }
    public class var navy: UIColor { return Cache.navy }
    public class var coral: UIColor { return Cache.coral }
    public class var white: UIColor { return Cache.white }
    public class var brandBlue: UIColor { return Cache.brandBlue }
    public class var brandAlt: UIColor { return Cache.brandAlt }
    public class var gradientWaterColor: UIColor { return Cache.gradientWaterColor }
    public class var gradientSandColor: UIColor { return Cache.gradientSandColor }
    public class var gradientSandColor2: UIColor { return Cache.gradientSandColor2 }
    public class var pureWhite: UIColor { return Cache.pureWhite }
    public class var darkWhite: UIColor { return Cache.darkWhite }

    //// Gradients

    public class var gradientBlue: CGGradient { return Cache.gradientBlue }
    public class var gradientWater: CGGradient { return Cache.gradientWater }
    public class var gradientSand: CGGradient { return Cache.gradientSand }

    //// Drawing Methods

    public class func drawKeepChoice(#filled: Bool) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let colorActive = filled ? StyleKit.pureWhite : StyleKit.teal
        let expression: CGFloat = filled ? 1 : 0.5

        //// keep
        CGContextSaveGState(context)
        CGContextSetAlpha(context, expression)
        CGContextBeginTransparencyLayer(context, nil)


        //// K-1 Drawing
        var k1Path = UIBezierPath()
        k1Path.moveToPoint(CGPointMake(89.69, 279.57))
        k1Path.addLineToPoint(CGPointMake(96.55, 281.54))
        k1Path.addLineToPoint(CGPointMake(93.01, 293.86))
        k1Path.addLineToPoint(CGPointMake(106.1, 284.28))
        k1Path.addLineToPoint(CGPointMake(114.16, 286.6))
        k1Path.addLineToPoint(CGPointMake(99.63, 297.28))
        k1Path.addLineToPoint(CGPointMake(106.4, 315.78))
        k1Path.addLineToPoint(CGPointMake(97.6, 313.25))
        k1Path.addLineToPoint(CGPointMake(91.96, 297.5))
        k1Path.addLineToPoint(CGPointMake(88.21, 310.56))
        k1Path.addLineToPoint(CGPointMake(81.35, 308.59))
        k1Path.addLineToPoint(CGPointMake(89.69, 279.57))
        k1Path.closePath()
        k1Path.miterLimit = 4;

        k1Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        k1Path.fill()


        //// E-2 Drawing
        var e2Path = UIBezierPath()
        e2Path.moveToPoint(CGPointMake(139.92, 312.97))
        e2Path.addLineToPoint(CGPointMake(139.5, 318.97))
        e2Path.addLineToPoint(CGPointMake(119.72, 317.58))
        e2Path.addLineToPoint(CGPointMake(121.83, 287.47))
        e2Path.addLineToPoint(CGPointMake(141.26, 288.84))
        e2Path.addLineToPoint(CGPointMake(140.84, 294.84))
        e2Path.addLineToPoint(CGPointMake(128.49, 293.97))
        e2Path.addLineToPoint(CGPointMake(128.07, 299.89))
        e2Path.addLineToPoint(CGPointMake(138.28, 300.61))
        e2Path.addLineToPoint(CGPointMake(137.86, 306.61))
        e2Path.addLineToPoint(CGPointMake(127.65, 305.9))
        e2Path.addLineToPoint(CGPointMake(127.22, 312.08))
        e2Path.addLineToPoint(CGPointMake(139.92, 312.97))
        e2Path.closePath()
        e2Path.miterLimit = 4;

        e2Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        e2Path.fill()


        //// E-3 Drawing
        var e3Path = UIBezierPath()
        e3Path.moveToPoint(CGPointMake(173.42, 310.02))
        e3Path.addLineToPoint(CGPointMake(174.17, 315.99))
        e3Path.addLineToPoint(CGPointMake(154.49, 318.46))
        e3Path.addLineToPoint(CGPointMake(150.74, 288.5))
        e3Path.addLineToPoint(CGPointMake(170.07, 286.08))
        e3Path.addLineToPoint(CGPointMake(170.82, 292.05))
        e3Path.addLineToPoint(CGPointMake(158.53, 293.59))
        e3Path.addLineToPoint(CGPointMake(159.27, 299.48))
        e3Path.addLineToPoint(CGPointMake(169.42, 298.21))
        e3Path.addLineToPoint(CGPointMake(170.17, 304.18))
        e3Path.addLineToPoint(CGPointMake(160.02, 305.46))
        e3Path.addLineToPoint(CGPointMake(160.79, 311.6))
        e3Path.addLineToPoint(CGPointMake(173.42, 310.02))
        e3Path.closePath()
        e3Path.miterLimit = 4;

        e3Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        e3Path.fill()


        //// E-4 Drawing
        var e4Path = UIBezierPath()
        e4Path.moveToPoint(CGPointMake(192.79, 302.01))
        e4Path.addLineToPoint(CGPointMake(195.58, 310.33))
        e4Path.addLineToPoint(CGPointMake(188.86, 312.59))
        e4Path.addLineToPoint(CGPointMake(179.34, 284.26))
        e4Path.addCurveToPoint(CGPointMake(203.4, 286.88), controlPoint1: CGPointMake(192.77, 276.98), controlPoint2: CGPointMake(200.88, 279.38))
        e4Path.addCurveToPoint(CGPointMake(192.79, 302.01), controlPoint1: CGPointMake(205.66, 293.61), controlPoint2: CGPointMake(202.23, 299.07))
        e4Path.addLineToPoint(CGPointMake(192.79, 302.01))
        e4Path.closePath()
        e4Path.moveToPoint(CGPointMake(190.8, 296.1))
        e4Path.addCurveToPoint(CGPointMake(196.44, 289.13), controlPoint1: CGPointMake(196.33, 294.47), controlPoint2: CGPointMake(197.45, 292.14))
        e4Path.addCurveToPoint(CGPointMake(187.94, 287.59), controlPoint1: CGPointMake(195.55, 286.48), controlPoint2: CGPointMake(192.72, 285.34))
        e4Path.addLineToPoint(CGPointMake(190.8, 296.1))
        e4Path.addLineToPoint(CGPointMake(190.8, 296.1))
        e4Path.closePath()
        e4Path.miterLimit = 4;

        e4Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        e4Path.fill()


        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(146.44, 33.44))
        bezierPath.addCurveToPoint(CGPointMake(148.4, 37.84), controlPoint1: CGPointMake(147.75, 34.74), controlPoint2: CGPointMake(148.4, 36.21))
        bezierPath.addCurveToPoint(CGPointMake(146.44, 42.49), controlPoint1: CGPointMake(148.4, 39.63), controlPoint2: CGPointMake(147.75, 41.18))
        bezierPath.addCurveToPoint(CGPointMake(141.8, 44.44), controlPoint1: CGPointMake(145.14, 43.79), controlPoint2: CGPointMake(143.59, 44.44))
        bezierPath.addCurveToPoint(CGPointMake(137.03, 42.49), controlPoint1: CGPointMake(139.84, 44.44), controlPoint2: CGPointMake(138.26, 43.79))
        bezierPath.addCurveToPoint(CGPointMake(135.2, 37.84), controlPoint1: CGPointMake(135.81, 41.18), controlPoint2: CGPointMake(135.2, 39.63))
        bezierPath.addCurveToPoint(CGPointMake(137.03, 33.32), controlPoint1: CGPointMake(135.2, 36.05), controlPoint2: CGPointMake(135.81, 34.54))
        bezierPath.addCurveToPoint(CGPointMake(141.8, 31.49), controlPoint1: CGPointMake(138.26, 32.1), controlPoint2: CGPointMake(139.84, 31.49))
        bezierPath.addCurveToPoint(CGPointMake(146.44, 33.44), controlPoint1: CGPointMake(143.59, 31.49), controlPoint2: CGPointMake(145.14, 32.14))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(141.31, 137.33))
        bezierPath.addCurveToPoint(CGPointMake(137.4, 138.8), controlPoint1: CGPointMake(140.01, 137.33), controlPoint2: CGPointMake(138.7, 137.82))
        bezierPath.addCurveToPoint(CGPointMake(135.2, 143.2), controlPoint1: CGPointMake(135.93, 139.94), controlPoint2: CGPointMake(135.2, 141.4))
        bezierPath.addCurveToPoint(CGPointMake(136.67, 147.11), controlPoint1: CGPointMake(135.2, 144.83), controlPoint2: CGPointMake(135.69, 146.13))
        bezierPath.addCurveToPoint(CGPointMake(141.31, 149.31), controlPoint1: CGPointMake(137.97, 148.57), controlPoint2: CGPointMake(139.52, 149.31))
        bezierPath.addCurveToPoint(CGPointMake(145.22, 147.84), controlPoint1: CGPointMake(142.78, 149.31), controlPoint2: CGPointMake(144.08, 148.82))
        bezierPath.addCurveToPoint(CGPointMake(147.18, 143.2), controlPoint1: CGPointMake(146.53, 146.54), controlPoint2: CGPointMake(147.18, 144.99))
        bezierPath.addCurveToPoint(CGPointMake(145.71, 139.29), controlPoint1: CGPointMake(147.18, 141.73), controlPoint2: CGPointMake(146.69, 140.43))
        bezierPath.addCurveToPoint(CGPointMake(141.31, 137.33), controlPoint1: CGPointMake(144.41, 137.98), controlPoint2: CGPointMake(142.94, 137.33))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(148.4, 136.84))
        bezierPath.addCurveToPoint(CGPointMake(150.84, 143.2), controlPoint1: CGPointMake(150.03, 138.96), controlPoint2: CGPointMake(150.84, 141.08))
        bezierPath.addCurveToPoint(CGPointMake(147.42, 150.29), controlPoint1: CGPointMake(150.84, 145.97), controlPoint2: CGPointMake(149.7, 148.33))
        bezierPath.addCurveToPoint(CGPointMake(141.31, 152.73), controlPoint1: CGPointMake(145.47, 151.92), controlPoint2: CGPointMake(143.43, 152.73))
        bezierPath.addCurveToPoint(CGPointMake(134.22, 149.31), controlPoint1: CGPointMake(138.54, 152.73), controlPoint2: CGPointMake(136.18, 151.59))
        bezierPath.addCurveToPoint(CGPointMake(131.78, 143.2), controlPoint1: CGPointMake(132.59, 147.35), controlPoint2: CGPointMake(131.78, 145.32))
        bezierPath.addCurveToPoint(CGPointMake(135.2, 135.86), controlPoint1: CGPointMake(131.78, 140.26), controlPoint2: CGPointMake(132.92, 137.82))
        bezierPath.addCurveToPoint(CGPointMake(141.31, 133.66), controlPoint1: CGPointMake(136.99, 134.4), controlPoint2: CGPointMake(139.03, 133.66))
        bezierPath.addCurveToPoint(CGPointMake(148.4, 136.84), controlPoint1: CGPointMake(144.41, 133.66), controlPoint2: CGPointMake(146.77, 134.72))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(190.44, 97))
        bezierPath.addCurveToPoint(CGPointMake(182.87, 99.44), controlPoint1: CGPointMake(188.49, 97), controlPoint2: CGPointMake(185.96, 97.81))
        bezierPath.addLineToPoint(CGPointMake(128.84, 125.11))
        bezierPath.addCurveToPoint(CGPointMake(125.42, 128.29), controlPoint1: CGPointMake(126.89, 126.25), controlPoint2: CGPointMake(125.75, 127.31))
        bezierPath.addLineToPoint(CGPointMake(92.18, 178.4))
        bezierPath.addCurveToPoint(CGPointMake(88.76, 186.46), controlPoint1: CGPointMake(89.9, 181.98), controlPoint2: CGPointMake(88.76, 184.67))
        bezierPath.addCurveToPoint(CGPointMake(92.18, 189.4), controlPoint1: CGPointMake(88.76, 188.42), controlPoint2: CGPointMake(89.9, 189.4))
        bezierPath.addCurveToPoint(CGPointMake(99.51, 187.2), controlPoint1: CGPointMake(93.97, 189.4), controlPoint2: CGPointMake(96.41, 188.66))
        bezierPath.addLineToPoint(CGPointMake(154.02, 161.04))
        bezierPath.addCurveToPoint(CGPointMake(157.44, 158.11), controlPoint1: CGPointMake(154.51, 160.88), controlPoint2: CGPointMake(155.65, 159.9))
        bezierPath.addLineToPoint(CGPointMake(190.44, 108.24))
        bezierPath.addCurveToPoint(CGPointMake(193.87, 99.93), controlPoint1: CGPointMake(192.73, 104.66), controlPoint2: CGPointMake(193.87, 101.89))
        bezierPath.addCurveToPoint(CGPointMake(190.44, 97), controlPoint1: CGPointMake(193.87, 97.97), controlPoint2: CGPointMake(192.73, 97))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(135.44, 62.53))
        bezierPath.addCurveToPoint(CGPointMake(135.44, 68.84), controlPoint1: CGPointMake(135.44, 62.53), controlPoint2: CGPointMake(135.44, 65.47))
        bezierPath.addCurveToPoint(CGPointMake(135.44, 78.66), controlPoint1: CGPointMake(135.44, 73.36), controlPoint2: CGPointMake(135.44, 78.66))
        bezierPath.addCurveToPoint(CGPointMake(136.06, 80.37), controlPoint1: CGPointMake(135.44, 79.32), controlPoint2: CGPointMake(135.65, 79.89))
        bezierPath.addCurveToPoint(CGPointMake(137.64, 81.11), controlPoint1: CGPointMake(136.46, 80.86), controlPoint2: CGPointMake(136.99, 81.11))
        bezierPath.addLineToPoint(CGPointMake(146.2, 81.11))
        bezierPath.addCurveToPoint(CGPointMake(147.79, 80.37), controlPoint1: CGPointMake(146.85, 81.11), controlPoint2: CGPointMake(147.38, 80.86))
        bezierPath.addCurveToPoint(CGPointMake(148.4, 78.66), controlPoint1: CGPointMake(148.2, 79.89), controlPoint2: CGPointMake(148.4, 79.32))
        bezierPath.addCurveToPoint(CGPointMake(148.4, 75.45), controlPoint1: CGPointMake(148.4, 78.66), controlPoint2: CGPointMake(148.4, 77.33))
        bezierPath.addCurveToPoint(CGPointMake(148.4, 62.77), controlPoint1: CGPointMake(148.4, 70.8), controlPoint2: CGPointMake(148.4, 62.77))
        bezierPath.addCurveToPoint(CGPointMake(183.97, 75), controlPoint1: CGPointMake(161.27, 63.92), controlPoint2: CGPointMake(173.13, 67.99))
        bezierPath.addCurveToPoint(CGPointMake(210, 102.13), controlPoint1: CGPointMake(194.8, 82), controlPoint2: CGPointMake(203.48, 91.05))
        bezierPath.addCurveToPoint(CGPointMake(220.51, 138.31), controlPoint1: CGPointMake(216.52, 113.21), controlPoint2: CGPointMake(220.02, 125.27))
        bezierPath.addLineToPoint(CGPointMake(203.89, 138.31))
        bezierPath.addCurveToPoint(CGPointMake(202.3, 139.04), controlPoint1: CGPointMake(203.24, 138.31), controlPoint2: CGPointMake(202.71, 138.55))
        bezierPath.addCurveToPoint(CGPointMake(201.69, 141), controlPoint1: CGPointMake(201.89, 139.53), controlPoint2: CGPointMake(201.69, 140.18))
        bezierPath.addLineToPoint(CGPointMake(201.69, 149.06))
        bezierPath.addCurveToPoint(CGPointMake(202.3, 150.77), controlPoint1: CGPointMake(201.69, 149.72), controlPoint2: CGPointMake(201.89, 150.29))
        bezierPath.addCurveToPoint(CGPointMake(203.89, 151.51), controlPoint1: CGPointMake(202.71, 151.26), controlPoint2: CGPointMake(203.24, 151.51))
        bezierPath.addLineToPoint(CGPointMake(220.02, 151.51))
        bezierPath.addCurveToPoint(CGPointMake(207.92, 185.24), controlPoint1: CGPointMake(218.56, 163.73), controlPoint2: CGPointMake(214.52, 174.97))
        bezierPath.addCurveToPoint(CGPointMake(182.38, 210.17), controlPoint1: CGPointMake(201.32, 195.51), controlPoint2: CGPointMake(192.81, 203.82))
        bezierPath.addCurveToPoint(CGPointMake(148.4, 221.42), controlPoint1: CGPointMake(171.95, 216.53), controlPoint2: CGPointMake(160.62, 220.28))
        bezierPath.addLineToPoint(CGPointMake(148.4, 205.04))
        bezierPath.addCurveToPoint(CGPointMake(147.79, 203.33), controlPoint1: CGPointMake(148.4, 204.39), controlPoint2: CGPointMake(148.2, 203.82))
        bezierPath.addCurveToPoint(CGPointMake(146.2, 202.6), controlPoint1: CGPointMake(147.38, 202.84), controlPoint2: CGPointMake(146.85, 202.6))
        bezierPath.addLineToPoint(CGPointMake(137.64, 202.6))
        bezierPath.addCurveToPoint(CGPointMake(136.06, 203.33), controlPoint1: CGPointMake(136.99, 202.6), controlPoint2: CGPointMake(136.46, 202.84))
        bezierPath.addCurveToPoint(CGPointMake(135.44, 205.04), controlPoint1: CGPointMake(135.65, 203.82), controlPoint2: CGPointMake(135.44, 204.39))
        bezierPath.addLineToPoint(CGPointMake(135.44, 221.42))
        bezierPath.addCurveToPoint(CGPointMake(100.61, 210.54), controlPoint1: CGPointMake(122.9, 220.6), controlPoint2: CGPointMake(111.29, 216.98))
        bezierPath.addCurveToPoint(CGPointMake(74.46, 185.49), controlPoint1: CGPointMake(89.94, 204.1), controlPoint2: CGPointMake(81.22, 195.75))
        bezierPath.addCurveToPoint(CGPointMake(62.11, 151.51), controlPoint1: CGPointMake(67.69, 175.22), controlPoint2: CGPointMake(63.58, 163.89))
        bezierPath.addLineToPoint(CGPointMake(78.24, 151.51))
        bezierPath.addCurveToPoint(CGPointMake(79.83, 150.77), controlPoint1: CGPointMake(78.9, 151.51), controlPoint2: CGPointMake(79.43, 151.26))
        bezierPath.addCurveToPoint(CGPointMake(80.44, 149.06), controlPoint1: CGPointMake(80.24, 150.29), controlPoint2: CGPointMake(80.44, 149.72))
        bezierPath.addLineToPoint(CGPointMake(80.44, 141))
        bezierPath.addCurveToPoint(CGPointMake(79.83, 139.04), controlPoint1: CGPointMake(80.44, 140.18), controlPoint2: CGPointMake(80.24, 139.53))
        bezierPath.addCurveToPoint(CGPointMake(78.24, 138.31), controlPoint1: CGPointMake(79.43, 138.55), controlPoint2: CGPointMake(78.9, 138.31))
        bezierPath.addLineToPoint(CGPointMake(61.62, 138.31))
        bezierPath.addCurveToPoint(CGPointMake(72.38, 101.64), controlPoint1: CGPointMake(62.11, 125.11), controlPoint2: CGPointMake(65.7, 112.89))
        bezierPath.addCurveToPoint(CGPointMake(99.02, 74.39), controlPoint1: CGPointMake(79.06, 90.4), controlPoint2: CGPointMake(87.94, 81.31))
        bezierPath.addCurveToPoint(CGPointMake(125.65, 63.84), controlPoint1: CGPointMake(107.31, 69.21), controlPoint2: CGPointMake(116.18, 65.69))
        bezierPath.addCurveToPoint(CGPointMake(135.44, 62.53), controlPoint1: CGPointMake(128.85, 63.21), controlPoint2: CGPointMake(132.11, 62.78))
        bezierPath.addLineToPoint(CGPointMake(135.44, 62.53))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(141.8, 18.29))
        bezierPath.addCurveToPoint(CGPointMake(127.87, 24.03), controlPoint1: CGPointMake(136.26, 18.29), controlPoint2: CGPointMake(131.61, 20.2))
        bezierPath.addCurveToPoint(CGPointMake(122.24, 37.84), controlPoint1: CGPointMake(124.12, 27.86), controlPoint2: CGPointMake(122.24, 32.46))
        bezierPath.addCurveToPoint(CGPointMake(124.44, 47.13), controlPoint1: CGPointMake(122.24, 41.26), controlPoint2: CGPointMake(122.98, 44.36))
        bezierPath.addCurveToPoint(CGPointMake(104.31, 52.95), controlPoint1: CGPointMake(117.41, 48.37), controlPoint2: CGPointMake(110.7, 50.31))
        bezierPath.addCurveToPoint(CGPointMake(84.23, 64.36), controlPoint1: CGPointMake(97.22, 55.89), controlPoint2: CGPointMake(90.53, 59.69))
        bezierPath.addCurveToPoint(CGPointMake(55.76, 97.61), controlPoint1: CGPointMake(72.26, 73.25), controlPoint2: CGPointMake(62.76, 84.33))
        bezierPath.addCurveToPoint(CGPointMake(45, 140.51), controlPoint1: CGPointMake(48.75, 110.89), controlPoint2: CGPointMake(45.16, 125.19))
        bezierPath.addLineToPoint(CGPointMake(45, 141))
        bezierPath.addLineToPoint(CGPointMake(45, 149.06))
        bezierPath.addCurveToPoint(CGPointMake(45.12, 149.8), controlPoint1: CGPointMake(45, 149.39), controlPoint2: CGPointMake(45.04, 149.63))
        bezierPath.addCurveToPoint(CGPointMake(45.24, 150.29), controlPoint1: CGPointMake(45.2, 149.96), controlPoint2: CGPointMake(45.24, 150.12))
        bezierPath.addCurveToPoint(CGPointMake(59.91, 193.8), controlPoint1: CGPointMake(46.55, 166.09), controlPoint2: CGPointMake(51.44, 180.6))
        bezierPath.addCurveToPoint(CGPointMake(92.79, 225.45), controlPoint1: CGPointMake(68.39, 207), controlPoint2: CGPointMake(79.34, 217.55))
        bezierPath.addCurveToPoint(CGPointMake(136.91, 238.29), controlPoint1: CGPointMake(106.23, 233.36), controlPoint2: CGPointMake(120.94, 237.63))
        bezierPath.addLineToPoint(CGPointMake(146.2, 238.29))
        bezierPath.addLineToPoint(CGPointMake(147.18, 238.04))
        bezierPath.addCurveToPoint(CGPointMake(190.44, 224.72), controlPoint1: CGPointMake(162.82, 237.06), controlPoint2: CGPointMake(177.24, 232.62))
        bezierPath.addCurveToPoint(CGPointMake(222.59, 193.31), controlPoint1: CGPointMake(203.64, 216.82), controlPoint2: CGPointMake(214.36, 206.35))
        bezierPath.addCurveToPoint(CGPointMake(236.89, 150.29), controlPoint1: CGPointMake(230.82, 180.27), controlPoint2: CGPointMake(235.59, 165.93))
        bezierPath.addCurveToPoint(CGPointMake(237.13, 149.8), controlPoint1: CGPointMake(236.89, 150.12), controlPoint2: CGPointMake(236.97, 149.96))
        bezierPath.addCurveToPoint(CGPointMake(237.38, 149.06), controlPoint1: CGPointMake(237.3, 149.63), controlPoint2: CGPointMake(237.38, 149.39))
        bezierPath.addLineToPoint(CGPointMake(237.38, 141))
        bezierPath.addLineToPoint(CGPointMake(237.38, 140.51))
        bezierPath.addCurveToPoint(CGPointMake(226.74, 97.97), controlPoint1: CGPointMake(237.21, 125.35), controlPoint2: CGPointMake(233.67, 111.17))
        bezierPath.addCurveToPoint(CGPointMake(198.51, 64.73), controlPoint1: CGPointMake(219.82, 84.77), controlPoint2: CGPointMake(210.41, 73.69))
        bezierPath.addCurveToPoint(CGPointMake(158.91, 47.13), controlPoint1: CGPointMake(186.61, 55.77), controlPoint2: CGPointMake(173.41, 49.9))
        bezierPath.addCurveToPoint(CGPointMake(161.11, 37.84), controlPoint1: CGPointMake(160.38, 44.36), controlPoint2: CGPointMake(161.11, 41.26))
        bezierPath.addCurveToPoint(CGPointMake(155.37, 24.03), controlPoint1: CGPointMake(161.11, 32.46), controlPoint2: CGPointMake(159.2, 27.86))
        bezierPath.addCurveToPoint(CGPointMake(141.8, 18.29), controlPoint1: CGPointMake(151.54, 20.2), controlPoint2: CGPointMake(147.01, 18.29))
        bezierPath.closePath()
        bezierPath.moveToPoint(CGPointMake(241.2, 39.33))
        bezierPath.addCurveToPoint(CGPointMake(241.2, 229.24), controlPoint1: CGPointMake(296.27, 91.77), controlPoint2: CGPointMake(296.27, 176.8))
        bezierPath.addCurveToPoint(CGPointMake(41.8, 229.24), controlPoint1: CGPointMake(186.14, 281.68), controlPoint2: CGPointMake(96.86, 281.68))
        bezierPath.addCurveToPoint(CGPointMake(41.8, 39.33), controlPoint1: CGPointMake(-13.27, 176.8), controlPoint2: CGPointMake(-13.27, 91.77))
        bezierPath.addLineToPoint(CGPointMake(42.02, 39.12))
        bezierPath.addCurveToPoint(CGPointMake(241.2, 39.33), controlPoint1: CGPointMake(97.1, -13.11), controlPoint2: CGPointMake(186.21, -13.04))
        bezierPath.closePath()
        colorActive.setFill()
        bezierPath.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    public class func drawSkipChoice(#filled: Bool) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let colorActive = filled ? StyleKit.pureWhite : StyleKit.teal
        let expression: CGFloat = filled ? 1 : 0.5

        //// skip
        CGContextSaveGState(context)
        CGContextSetAlpha(context, expression)
        CGContextBeginTransparencyLayer(context, nil)


        //// Oval-5 Drawing
        var oval5Path = UIBezierPath()
        oval5Path.moveToPoint(CGPointMake(141.75, 268.57))
        oval5Path.addCurveToPoint(CGPointMake(282.75, 134.29), controlPoint1: CGPointMake(219.62, 268.57), controlPoint2: CGPointMake(282.75, 208.45))
        oval5Path.addCurveToPoint(CGPointMake(141.75, 0), controlPoint1: CGPointMake(282.75, 60.12), controlPoint2: CGPointMake(219.62, 0))
        oval5Path.addCurveToPoint(CGPointMake(0.75, 134.29), controlPoint1: CGPointMake(63.88, 0), controlPoint2: CGPointMake(0.75, 60.12))
        oval5Path.addCurveToPoint(CGPointMake(141.75, 268.57), controlPoint1: CGPointMake(0.75, 208.45), controlPoint2: CGPointMake(63.88, 268.57))
        oval5Path.closePath()
        oval5Path.moveToPoint(CGPointMake(231.89, 194.92))
        oval5Path.addCurveToPoint(CGPointMake(227.81, 197.12), controlPoint1: CGPointMake(230.84, 196.25), controlPoint2: CGPointMake(229.48, 196.98))
        oval5Path.addLineToPoint(CGPointMake(226.98, 197.12))
        oval5Path.addCurveToPoint(CGPointMake(222.9, 195.65), controlPoint1: CGPointMake(225.44, 197.12), controlPoint2: CGPointMake(224.09, 196.63))
        oval5Path.addCurveToPoint(CGPointMake(220.92, 191.89), controlPoint1: CGPointMake(221.72, 194.68), controlPoint2: CGPointMake(221.06, 193.43))
        oval5Path.addLineToPoint(CGPointMake(218.83, 176.02))
        oval5Path.addCurveToPoint(CGPointMake(189.9, 202.65), controlPoint1: CGPointMake(211.03, 186.88), controlPoint2: CGPointMake(201.39, 195.76))
        oval5Path.addCurveToPoint(CGPointMake(152.82, 215.08), controlPoint1: CGPointMake(178.41, 209.55), controlPoint2: CGPointMake(166.05, 213.69))
        oval5Path.addLineToPoint(CGPointMake(152.82, 219.47))
        oval5Path.addCurveToPoint(CGPointMake(149.79, 226.36), controlPoint1: CGPointMake(152.82, 222.11), controlPoint2: CGPointMake(151.81, 224.41))
        oval5Path.addCurveToPoint(CGPointMake(142.59, 229.29), controlPoint1: CGPointMake(147.77, 228.31), controlPoint2: CGPointMake(145.37, 229.29))
        oval5Path.addCurveToPoint(CGPointMake(135.38, 226.36), controlPoint1: CGPointMake(139.8, 229.29), controlPoint2: CGPointMake(137.4, 228.31))
        oval5Path.addCurveToPoint(CGPointMake(132.35, 219.47), controlPoint1: CGPointMake(133.36, 224.41), controlPoint2: CGPointMake(132.35, 222.11))
        oval5Path.addLineToPoint(CGPointMake(132.35, 215.08))
        oval5Path.addCurveToPoint(CGPointMake(94.85, 202.44), controlPoint1: CGPointMake(118.98, 213.69), controlPoint2: CGPointMake(106.48, 209.48))
        oval5Path.addCurveToPoint(CGPointMake(65.51, 175.18), controlPoint1: CGPointMake(83.23, 195.41), controlPoint2: CGPointMake(73.44, 186.32))
        oval5Path.addLineToPoint(CGPointMake(63.42, 191.89))
        oval5Path.addCurveToPoint(CGPointMake(61.54, 195.65), controlPoint1: CGPointMake(63.28, 193.43), controlPoint2: CGPointMake(62.65, 194.68))
        oval5Path.addCurveToPoint(CGPointMake(57.36, 197.12), controlPoint1: CGPointMake(60.42, 196.63), controlPoint2: CGPointMake(59.03, 197.12))
        oval5Path.addLineToPoint(CGPointMake(56.73, 197.12))
        oval5Path.addCurveToPoint(CGPointMake(52.66, 194.82), controlPoint1: CGPointMake(55.06, 196.84), controlPoint2: CGPointMake(53.7, 196.07))
        oval5Path.addCurveToPoint(CGPointMake(51.3, 190.64), controlPoint1: CGPointMake(51.61, 193.57), controlPoint2: CGPointMake(51.16, 192.17))
        oval5Path.addLineToPoint(CGPointMake(55.48, 156.17))
        oval5Path.addCurveToPoint(CGPointMake(57.67, 152.41), controlPoint1: CGPointMake(55.76, 154.64), controlPoint2: CGPointMake(56.49, 153.39))
        oval5Path.addCurveToPoint(CGPointMake(61.75, 150.95), controlPoint1: CGPointMake(58.86, 151.44), controlPoint2: CGPointMake(60.21, 150.95))
        oval5Path.addLineToPoint(CGPointMake(94.75, 150.95))
        oval5Path.addCurveToPoint(CGPointMake(99.03, 152.73), controlPoint1: CGPointMake(96.42, 150.95), controlPoint2: CGPointMake(97.85, 151.54))
        oval5Path.addCurveToPoint(CGPointMake(100.81, 156.8), controlPoint1: CGPointMake(100.22, 153.91), controlPoint2: CGPointMake(100.81, 155.27))
        oval5Path.addCurveToPoint(CGPointMake(99.03, 160.98), controlPoint1: CGPointMake(100.81, 158.47), controlPoint2: CGPointMake(100.22, 159.86))
        oval5Path.addCurveToPoint(CGPointMake(94.75, 162.65), controlPoint1: CGPointMake(97.85, 162.09), controlPoint2: CGPointMake(96.42, 162.65))
        oval5Path.addLineToPoint(CGPointMake(76.79, 162.65))
        oval5Path.addCurveToPoint(CGPointMake(100.7, 187.3), controlPoint1: CGPointMake(83.05, 172.68), controlPoint2: CGPointMake(91.02, 180.89))
        oval5Path.addCurveToPoint(CGPointMake(132.35, 199.21), controlPoint1: CGPointMake(110.38, 193.71), controlPoint2: CGPointMake(120.93, 197.67))
        oval5Path.addLineToPoint(CGPointMake(132.35, 134.45))
        oval5Path.addLineToPoint(CGPointMake(110.21, 134.45))
        oval5Path.addLineToPoint(CGPointMake(110.21, 120.66))
        oval5Path.addLineToPoint(CGPointMake(132.35, 120.66))
        oval5Path.addLineToPoint(CGPointMake(132.35, 105.21))
        oval5Path.addCurveToPoint(CGPointMake(114.8, 93.93), controlPoint1: CGPointMake(125.11, 103.12), controlPoint2: CGPointMake(119.26, 99.36))
        oval5Path.addCurveToPoint(CGPointMake(108.12, 75.54), controlPoint1: CGPointMake(110.35, 88.49), controlPoint2: CGPointMake(108.12, 82.37))
        oval5Path.addCurveToPoint(CGPointMake(112.82, 58.1), controlPoint1: CGPointMake(108.12, 69.14), controlPoint2: CGPointMake(109.69, 63.32))
        oval5Path.addCurveToPoint(CGPointMake(125.77, 45.78), controlPoint1: CGPointMake(115.95, 52.88), controlPoint2: CGPointMake(120.27, 48.77))
        oval5Path.addCurveToPoint(CGPointMake(144.05, 41.29), controlPoint1: CGPointMake(131.27, 42.78), controlPoint2: CGPointMake(137.36, 41.29))
        oval5Path.addCurveToPoint(CGPointMake(160.55, 45.88), controlPoint1: CGPointMake(150.04, 41.29), controlPoint2: CGPointMake(155.54, 42.82))
        oval5Path.addCurveToPoint(CGPointMake(172.56, 58.31), controlPoint1: CGPointMake(165.56, 48.94), controlPoint2: CGPointMake(169.57, 53.09))
        oval5Path.addCurveToPoint(CGPointMake(177.05, 75.54), controlPoint1: CGPointMake(175.56, 63.53), controlPoint2: CGPointMake(177.05, 69.28))
        oval5Path.addCurveToPoint(CGPointMake(170.05, 94.24), controlPoint1: CGPointMake(177.05, 82.37), controlPoint2: CGPointMake(174.72, 88.6))
        oval5Path.addCurveToPoint(CGPointMake(152.82, 105.62), controlPoint1: CGPointMake(165.39, 99.88), controlPoint2: CGPointMake(159.64, 103.67))
        oval5Path.addLineToPoint(CGPointMake(152.82, 120.66))
        oval5Path.addLineToPoint(CGPointMake(174.96, 120.66))
        oval5Path.addLineToPoint(CGPointMake(174.96, 134.45))
        oval5Path.addLineToPoint(CGPointMake(152.82, 134.45))
        oval5Path.addLineToPoint(CGPointMake(152.82, 199.21))
        oval5Path.addCurveToPoint(CGPointMake(184.47, 187.3), controlPoint1: CGPointMake(164.24, 197.67), controlPoint2: CGPointMake(174.79, 193.71))
        oval5Path.addCurveToPoint(CGPointMake(208.18, 162.65), controlPoint1: CGPointMake(194.15, 180.89), controlPoint2: CGPointMake(202.05, 172.68))
        oval5Path.addLineToPoint(CGPointMake(189.59, 162.65))
        oval5Path.addCurveToPoint(CGPointMake(185.3, 160.98), controlPoint1: CGPointMake(187.91, 162.65), controlPoint2: CGPointMake(186.49, 162.09))
        oval5Path.addCurveToPoint(CGPointMake(183.53, 156.8), controlPoint1: CGPointMake(184.12, 159.86), controlPoint2: CGPointMake(183.53, 158.47))
        oval5Path.addCurveToPoint(CGPointMake(185.3, 152.73), controlPoint1: CGPointMake(183.53, 155.27), controlPoint2: CGPointMake(184.12, 153.91))
        oval5Path.addCurveToPoint(CGPointMake(189.59, 150.95), controlPoint1: CGPointMake(186.49, 151.54), controlPoint2: CGPointMake(187.91, 150.95))
        oval5Path.addLineToPoint(CGPointMake(222.8, 150.95))
        oval5Path.addCurveToPoint(CGPointMake(226.77, 152.41), controlPoint1: CGPointMake(224.33, 150.95), controlPoint2: CGPointMake(225.65, 151.44))
        oval5Path.addCurveToPoint(CGPointMake(228.86, 156.17), controlPoint1: CGPointMake(227.88, 153.39), controlPoint2: CGPointMake(228.58, 154.64))
        oval5Path.addLineToPoint(CGPointMake(233.03, 190.64))
        oval5Path.addCurveToPoint(CGPointMake(231.89, 194.92), controlPoint1: CGPointMake(233.31, 192.17), controlPoint2: CGPointMake(232.93, 193.6))
        oval5Path.closePath()
        oval5Path.moveToPoint(CGPointMake(156.37, 87.24))
        oval5Path.addCurveToPoint(CGPointMake(161.8, 75.54), controlPoint1: CGPointMake(159.99, 83.76), controlPoint2: CGPointMake(161.8, 79.86))
        oval5Path.addCurveToPoint(CGPointMake(156.48, 61.34), controlPoint1: CGPointMake(161.8, 69.83), controlPoint2: CGPointMake(160.03, 65.1))
        oval5Path.addCurveToPoint(CGPointMake(144.05, 55.7), controlPoint1: CGPointMake(152.93, 57.58), controlPoint2: CGPointMake(148.78, 55.7))
        oval5Path.addCurveToPoint(CGPointMake(129.01, 61.23), controlPoint1: CGPointMake(137.92, 55.7), controlPoint2: CGPointMake(132.91, 57.54))
        oval5Path.addCurveToPoint(CGPointMake(123.16, 75.54), controlPoint1: CGPointMake(125.11, 64.92), controlPoint2: CGPointMake(123.16, 69.69))
        oval5Path.addCurveToPoint(CGPointMake(129.22, 87.35), controlPoint1: CGPointMake(123.16, 80), controlPoint2: CGPointMake(125.18, 83.93))
        oval5Path.addCurveToPoint(CGPointMake(144.05, 92.46), controlPoint1: CGPointMake(133.26, 90.76), controlPoint2: CGPointMake(138.2, 92.46))
        oval5Path.addCurveToPoint(CGPointMake(156.37, 87.24), controlPoint1: CGPointMake(148.64, 92.46), controlPoint2: CGPointMake(152.75, 90.72))
        oval5Path.closePath()
        oval5Path.miterLimit = 4;

        oval5Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        oval5Path.fill()


        //// Fill-5 Drawing
        var fill5Path = UIBezierPath()
        fill5Path.moveToPoint(CGPointMake(108.32, 291.88))
        fill5Path.addCurveToPoint(CGPointMake(102.41, 288.15), controlPoint1: CGPointMake(106.84, 290.42), controlPoint2: CGPointMake(104.37, 288.66))
        fill5Path.addCurveToPoint(CGPointMake(97.58, 289.46), controlPoint1: CGPointMake(100.12, 287.55), controlPoint2: CGPointMake(97.99, 287.88))
        fill5Path.addCurveToPoint(CGPointMake(101.65, 294.44), controlPoint1: CGPointMake(97.16, 291.04), controlPoint2: CGPointMake(98.96, 292.49))
        fill5Path.addCurveToPoint(CGPointMake(107.86, 306.34), controlPoint1: CGPointMake(108.13, 299.21), controlPoint2: CGPointMake(108.84, 302.95))
        fill5Path.addCurveToPoint(CGPointMake(94.58, 311.88), controlPoint1: CGPointMake(106.34, 311.64), controlPoint2: CGPointMake(100.6, 313.51))
        fill5Path.addCurveToPoint(CGPointMake(85.36, 305.68), controlPoint1: CGPointMake(90.35, 310.73), controlPoint2: CGPointMake(86.83, 307.71))
        fill5Path.addLineToPoint(CGPointMake(89.24, 301.06))
        fill5Path.addCurveToPoint(CGPointMake(95.73, 305.65), controlPoint1: CGPointMake(90.56, 302.65), controlPoint2: CGPointMake(93.11, 304.96))
        fill5Path.addCurveToPoint(CGPointMake(100.94, 304.57), controlPoint1: CGPointMake(97.68, 306.16), controlPoint2: CGPointMake(100.45, 306.44))
        fill5Path.addCurveToPoint(CGPointMake(95.46, 298.55), controlPoint1: CGPointMake(101.46, 302.62), controlPoint2: CGPointMake(98.08, 300.75))
        fill5Path.addCurveToPoint(CGPointMake(90.67, 287.65), controlPoint1: CGPointMake(91.66, 295.38), controlPoint2: CGPointMake(89.54, 291.97))
        fill5Path.addCurveToPoint(CGPointMake(103.42, 281.75), controlPoint1: CGPointMake(91.84, 283.2), controlPoint2: CGPointMake(96.85, 280.02))
        fill5Path.addCurveToPoint(CGPointMake(112.03, 286.72), controlPoint1: CGPointMake(107.13, 282.72), controlPoint2: CGPointMake(110.82, 285.6))
        fill5Path.addLineToPoint(CGPointMake(108.32, 291.88))
        fill5Path.closePath()
        fill5Path.miterLimit = 4;

        fill5Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill5Path.fill()


        //// Fill-6 Drawing
        var fill6Path = UIBezierPath()
        fill6Path.moveToPoint(CGPointMake(122.24, 286.4))
        fill6Path.addLineToPoint(CGPointMake(129.37, 286.73))
        fill6Path.addLineToPoint(CGPointMake(128.79, 299.53))
        fill6Path.addLineToPoint(CGPointMake(139.29, 287.17))
        fill6Path.addLineToPoint(CGPointMake(147.67, 287.55))
        fill6Path.addLineToPoint(CGPointMake(136.03, 301.31))
        fill6Path.addLineToPoint(CGPointMake(146.91, 317.73))
        fill6Path.addLineToPoint(CGPointMake(137.76, 317.32))
        fill6Path.addLineToPoint(CGPointMake(128.62, 303.3))
        fill6Path.addLineToPoint(CGPointMake(128.01, 316.88))
        fill6Path.addLineToPoint(CGPointMake(120.88, 316.56))
        fill6Path.addLineToPoint(CGPointMake(122.24, 286.4))
        fill6Path.closePath()
        fill6Path.miterLimit = 4;

        fill6Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill6Path.fill()


        //// Fill-7 Drawing
        var fill7Path = UIBezierPath()
        fill7Path.moveToPoint(CGPointMake(155.87, 286.3))
        fill7Path.addLineToPoint(CGPointMake(162.91, 285.39))
        fill7Path.addLineToPoint(CGPointMake(166.78, 315.33))
        fill7Path.addLineToPoint(CGPointMake(159.74, 316.24))
        fill7Path.addLineToPoint(CGPointMake(155.87, 286.3))
        fill7Path.closePath()
        fill7Path.miterLimit = 4;

        fill7Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill7Path.fill()


        //// Fill-8 Drawing
        var fill8Path = UIBezierPath()
        fill8Path.moveToPoint(CGPointMake(186.42, 302.14))
        fill8Path.addLineToPoint(CGPointMake(188.95, 310.54))
        fill8Path.addLineToPoint(CGPointMake(182.15, 312.58))
        fill8Path.addLineToPoint(CGPointMake(173.55, 283.96))
        fill8Path.addCurveToPoint(CGPointMake(197.52, 287.36), controlPoint1: CGPointMake(187.21, 277.12), controlPoint2: CGPointMake(195.24, 279.78))
        fill8Path.addCurveToPoint(CGPointMake(186.42, 302.14), controlPoint1: CGPointMake(199.56, 294.16), controlPoint2: CGPointMake(195.96, 299.5))
        fill8Path.addLineToPoint(CGPointMake(186.42, 302.14))
        fill8Path.closePath()
        fill8Path.moveToPoint(CGPointMake(184.63, 296.17))
        fill8Path.addCurveToPoint(CGPointMake(190.49, 289.38), controlPoint1: CGPointMake(190.21, 294.72), controlPoint2: CGPointMake(191.41, 292.43))
        fill8Path.addCurveToPoint(CGPointMake(182.04, 287.56), controlPoint1: CGPointMake(189.68, 286.7), controlPoint2: CGPointMake(186.89, 285.48))
        fill8Path.addLineToPoint(CGPointMake(184.63, 296.17))
        fill8Path.addLineToPoint(CGPointMake(184.63, 296.17))
        fill8Path.closePath()
        fill8Path.miterLimit = 4;

        fill8Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill8Path.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    public class func drawMarryChoice(#filled: Bool) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Variable Declarations
        let colorActive = filled ? StyleKit.pureWhite : StyleKit.teal
        let expression: CGFloat = filled ? 1 : 0.5

        //// Group
        CGContextSaveGState(context)
        CGContextSetAlpha(context, expression)
        CGContextBeginTransparencyLayer(context, nil)


        //// e Drawing
        var ePath = UIBezierPath()
        ePath.moveToPoint(CGPointMake(211.65, 18.02))
        ePath.addCurveToPoint(CGPointMake(263.07, 66.85), controlPoint1: CGPointMake(233.31, 30.03), controlPoint2: CGPointMake(250.45, 46.3))
        ePath.addCurveToPoint(CGPointMake(282, 134), controlPoint1: CGPointMake(275.69, 87.4), controlPoint2: CGPointMake(282, 109.78))
        ePath.addCurveToPoint(CGPointMake(263.07, 201.15), controlPoint1: CGPointMake(282, 158.22), controlPoint2: CGPointMake(275.69, 180.6))
        ePath.addCurveToPoint(CGPointMake(211.65, 249.98), controlPoint1: CGPointMake(250.45, 221.7), controlPoint2: CGPointMake(233.31, 237.97))
        ePath.addCurveToPoint(CGPointMake(141, 268), controlPoint1: CGPointMake(189.99, 261.99), controlPoint2: CGPointMake(166.44, 268))
        ePath.addCurveToPoint(CGPointMake(70.35, 249.98), controlPoint1: CGPointMake(115.56, 268), controlPoint2: CGPointMake(92.01, 261.99))
        ePath.addCurveToPoint(CGPointMake(18.93, 201.15), controlPoint1: CGPointMake(48.69, 237.97), controlPoint2: CGPointMake(31.55, 221.7))
        ePath.addCurveToPoint(CGPointMake(0, 134), controlPoint1: CGPointMake(6.31, 180.6), controlPoint2: CGPointMake(0, 158.22))
        ePath.addCurveToPoint(CGPointMake(18.93, 66.85), controlPoint1: CGPointMake(0, 109.78), controlPoint2: CGPointMake(6.31, 87.4))
        ePath.addCurveToPoint(CGPointMake(70.35, 18.02), controlPoint1: CGPointMake(31.55, 46.3), controlPoint2: CGPointMake(48.69, 30.03))
        ePath.addCurveToPoint(CGPointMake(141, 0), controlPoint1: CGPointMake(92.01, 6.01), controlPoint2: CGPointMake(115.56, 0))
        ePath.addCurveToPoint(CGPointMake(211.65, 18.02), controlPoint1: CGPointMake(166.44, 0), controlPoint2: CGPointMake(189.99, 6.01))
        ePath.addLineToPoint(CGPointMake(211.65, 18.02))
        ePath.closePath()
        ePath.moveToPoint(CGPointMake(56.34, 121.2))
        ePath.addLineToPoint(CGPointMake(76.31, 121.2))
        ePath.addCurveToPoint(CGPointMake(96.58, 111.96), controlPoint1: CGPointMake(83.07, 115.04), controlPoint2: CGPointMake(89.83, 111.96))
        ePath.addCurveToPoint(CGPointMake(111.04, 115.54), controlPoint1: CGPointMake(102.15, 111.96), controlPoint2: CGPointMake(106.97, 113.16))
        ePath.addCurveToPoint(CGPointMake(121.03, 124.17), controlPoint1: CGPointMake(115.12, 117.92), controlPoint2: CGPointMake(118.44, 120.8))
        ePath.addCurveToPoint(CGPointMake(130.27, 137.87), controlPoint1: CGPointMake(123.61, 127.55), controlPoint2: CGPointMake(126.69, 132.11))
        ePath.addCurveToPoint(CGPointMake(143.68, 130.13), controlPoint1: CGPointMake(133.25, 135.89), controlPoint2: CGPointMake(137.72, 133.31))
        ePath.addCurveToPoint(CGPointMake(138.47, 121.79), controlPoint1: CGPointMake(142.89, 128.34), controlPoint2: CGPointMake(141.15, 125.56))
        ePath.addCurveToPoint(CGPointMake(130.27, 111.37), controlPoint1: CGPointMake(135.78, 118.02), controlPoint2: CGPointMake(133.05, 114.55))
        ePath.addCurveToPoint(CGPointMake(96.58, 96.48), controlPoint1: CGPointMake(121.52, 101.44), controlPoint2: CGPointMake(110.3, 96.48))
        ePath.addCurveToPoint(CGPointMake(64.39, 111.67), controlPoint1: CGPointMake(85.26, 96.48), controlPoint2: CGPointMake(74.52, 101.54))
        ePath.addCurveToPoint(CGPointMake(56.34, 121.2), controlPoint1: CGPointMake(62.6, 113.25), controlPoint2: CGPointMake(59.92, 116.43))
        ePath.addLineToPoint(CGPointMake(56.34, 121.2))
        ePath.closePath()
        ePath.moveToPoint(CGPointMake(86.15, 142.34))
        ePath.addCurveToPoint(CGPointMake(91.52, 142.04), controlPoint1: CGPointMake(88.53, 142.34), controlPoint2: CGPointMake(90.32, 142.24))
        ePath.addCurveToPoint(CGPointMake(121.62, 135.19), controlPoint1: CGPointMake(102.05, 141.64), controlPoint2: CGPointMake(112.08, 139.36))
        ePath.addCurveToPoint(CGPointMake(111.49, 122.98), controlPoint1: CGPointMake(118.25, 129.63), controlPoint2: CGPointMake(114.87, 125.56))
        ePath.addCurveToPoint(CGPointMake(90.92, 127.15), controlPoint1: CGPointMake(104.53, 125.56), controlPoint2: CGPointMake(97.68, 126.95))
        ePath.addLineToPoint(CGPointMake(86.15, 127.15))
        ePath.addLineToPoint(CGPointMake(28.92, 127.15))
        ePath.addCurveToPoint(CGPointMake(23.55, 129.09), controlPoint1: CGPointMake(26.93, 127.15), controlPoint2: CGPointMake(25.14, 127.8))
        ePath.addCurveToPoint(CGPointMake(20.87, 134), controlPoint1: CGPointMake(21.96, 130.38), controlPoint2: CGPointMake(21.07, 132.01))
        ePath.addLineToPoint(CGPointMake(20.87, 135.19))
        ePath.addCurveToPoint(CGPointMake(22.66, 139.96), controlPoint1: CGPointMake(20.87, 137.18), controlPoint2: CGPointMake(21.46, 138.76))
        ePath.addCurveToPoint(CGPointMake(28.62, 142.34), controlPoint1: CGPointMake(24.64, 141.54), controlPoint2: CGPointMake(26.63, 142.34))
        ePath.addLineToPoint(CGPointMake(86.15, 142.34))
        ePath.closePath()
        ePath.moveToPoint(CGPointMake(158.89, 147.4))
        ePath.addCurveToPoint(CGPointMake(193.47, 141.44), controlPoint1: CGPointMake(169.02, 143.43), controlPoint2: CGPointMake(180.55, 141.44))
        ePath.addLineToPoint(CGPointMake(201.22, 141.44))
        ePath.addCurveToPoint(CGPointMake(203, 134.89), controlPoint1: CGPointMake(202.41, 139.26), controlPoint2: CGPointMake(203, 137.08))
        ePath.addCurveToPoint(CGPointMake(200.32, 127.15), controlPoint1: CGPointMake(203, 132.11), controlPoint2: CGPointMake(202.11, 129.53))
        ePath.addLineToPoint(CGPointMake(199.73, 126.26))
        ePath.addLineToPoint(CGPointMake(193.47, 126.26))
        ePath.addCurveToPoint(CGPointMake(148.15, 134.89), controlPoint1: CGPointMake(177.57, 126.26), controlPoint2: CGPointMake(162.46, 129.14))
        ePath.addCurveToPoint(CGPointMake(132.06, 143.83), controlPoint1: CGPointMake(142.59, 137.47), controlPoint2: CGPointMake(137.22, 140.45))
        ePath.addLineToPoint(CGPointMake(131.46, 144.42))
        ePath.addLineToPoint(CGPointMake(128.78, 145.91))
        ePath.addLineToPoint(CGPointMake(127.88, 146.51))
        ePath.addCurveToPoint(CGPointMake(113.13, 155.14), controlPoint1: CGPointMake(122.12, 150.48), controlPoint2: CGPointMake(117.2, 153.36))
        ePath.addCurveToPoint(CGPointMake(96.58, 157.82), controlPoint1: CGPointMake(109.05, 156.93), controlPoint2: CGPointMake(103.54, 157.82))
        ePath.addCurveToPoint(CGPointMake(78.7, 152.76), controlPoint1: CGPointMake(90.82, 157.82), controlPoint2: CGPointMake(84.86, 156.13))
        ePath.addCurveToPoint(CGPointMake(73.63, 148.29), controlPoint1: CGPointMake(77.7, 152.16), controlPoint2: CGPointMake(76.01, 150.68))
        ePath.addLineToPoint(CGPointMake(55.15, 148.29))
        ePath.addCurveToPoint(CGPointMake(70.05, 165.56), controlPoint1: CGPointMake(57.93, 154.84), controlPoint2: CGPointMake(62.9, 160.6))
        ePath.addCurveToPoint(CGPointMake(96.58, 173.01), controlPoint1: CGPointMake(79, 170.53), controlPoint2: CGPointMake(87.84, 173.01))
        ePath.addCurveToPoint(CGPointMake(117.15, 169.88), controlPoint1: CGPointMake(105.13, 173.01), controlPoint2: CGPointMake(111.99, 171.97))
        ePath.addCurveToPoint(CGPointMake(135.34, 159.91), controlPoint1: CGPointMake(122.32, 167.8), controlPoint2: CGPointMake(128.38, 164.47))
        ePath.addCurveToPoint(CGPointMake(158.89, 147.4), controlPoint1: CGPointMake(143.48, 154.35), controlPoint2: CGPointMake(151.33, 150.18))
        ePath.addLineToPoint(CGPointMake(158.89, 147.4))
        ePath.closePath()
        ePath.moveToPoint(CGPointMake(225.06, 134.3))
        ePath.addCurveToPoint(CGPointMake(223.27, 125.07), controlPoint1: CGPointMake(225.06, 131.12), controlPoint2: CGPointMake(224.47, 128.04))
        ePath.addCurveToPoint(CGPointMake(207.77, 105.41), controlPoint1: CGPointMake(220.89, 116.73), controlPoint2: CGPointMake(215.72, 110.18))
        ePath.addCurveToPoint(CGPointMake(179.75, 96.48), controlPoint1: CGPointMake(199.23, 99.46), controlPoint2: CGPointMake(189.89, 96.48))
        ePath.addCurveToPoint(CGPointMake(136.83, 109.58), controlPoint1: CGPointMake(166.04, 96.48), controlPoint2: CGPointMake(151.73, 100.85))
        ePath.addCurveToPoint(CGPointMake(142.94, 117.18), controlPoint1: CGPointMake(139.21, 112.16), controlPoint2: CGPointMake(141.25, 114.69))
        ePath.addCurveToPoint(CGPointMake(146.07, 122.09), controlPoint1: CGPointMake(144.63, 119.66), controlPoint2: CGPointMake(145.67, 121.29))
        ePath.addCurveToPoint(CGPointMake(179.75, 111.96), controlPoint1: CGPointMake(157.2, 115.34), controlPoint2: CGPointMake(168.42, 111.96))
        ePath.addCurveToPoint(CGPointMake(198.83, 117.92), controlPoint1: CGPointMake(187.3, 111.96), controlPoint2: CGPointMake(193.66, 113.95))
        ePath.addCurveToPoint(CGPointMake(205.39, 123.28), controlPoint1: CGPointMake(200.62, 118.91), controlPoint2: CGPointMake(202.81, 120.7))
        ePath.addCurveToPoint(CGPointMake(209.26, 134.89), controlPoint1: CGPointMake(207.97, 126.85), controlPoint2: CGPointMake(209.26, 130.72))
        ePath.addCurveToPoint(CGPointMake(206.88, 143.83), controlPoint1: CGPointMake(209.26, 138.07), controlPoint2: CGPointMake(208.47, 141.05))
        ePath.addCurveToPoint(CGPointMake(198.83, 152.16), controlPoint1: CGPointMake(205.49, 146.21), controlPoint2: CGPointMake(202.81, 148.99))
        ePath.addCurveToPoint(CGPointMake(179.75, 157.82), controlPoint1: CGPointMake(193.27, 155.94), controlPoint2: CGPointMake(186.91, 157.82))
        ePath.addCurveToPoint(CGPointMake(161.57, 152.76), controlPoint1: CGPointMake(172.8, 157.82), controlPoint2: CGPointMake(166.74, 156.13))
        ePath.addCurveToPoint(CGPointMake(146.37, 160.2), controlPoint1: CGPointMake(157.2, 154.15), controlPoint2: CGPointMake(152.13, 156.63))
        ePath.addCurveToPoint(CGPointMake(179.75, 173.01), controlPoint1: CGPointMake(155.51, 168.74), controlPoint2: CGPointMake(166.64, 173.01))
        ePath.addCurveToPoint(CGPointMake(207.77, 164.37), controlPoint1: CGPointMake(189.89, 173.01), controlPoint2: CGPointMake(199.23, 170.13))
        ePath.addCurveToPoint(CGPointMake(223.87, 142.64), controlPoint1: CGPointMake(216.32, 158.62), controlPoint2: CGPointMake(221.68, 151.37))
        ePath.addCurveToPoint(CGPointMake(225.06, 134.3), controlPoint1: CGPointMake(224.67, 139.06), controlPoint2: CGPointMake(225.06, 136.28))
        ePath.addLineToPoint(CGPointMake(225.06, 134.3))
        ePath.closePath()
        ePath.moveToPoint(CGPointMake(261.43, 138.76))
        ePath.addCurveToPoint(CGPointMake(263.22, 134), controlPoint1: CGPointMake(262.62, 137.18), controlPoint2: CGPointMake(263.22, 135.59))
        ePath.addCurveToPoint(CGPointMake(260.98, 128.49), controlPoint1: CGPointMake(263.22, 131.82), controlPoint2: CGPointMake(262.47, 129.98))
        ePath.addCurveToPoint(CGPointMake(255.17, 126.26), controlPoint1: CGPointMake(259.49, 127), controlPoint2: CGPointMake(257.56, 126.26))
        ePath.addLineToPoint(CGPointMake(229.83, 126.26))
        ePath.addCurveToPoint(CGPointMake(230.73, 134.3), controlPoint1: CGPointMake(230.43, 128.84), controlPoint2: CGPointMake(230.73, 131.52))
        ePath.addCurveToPoint(CGPointMake(230.13, 141.44), controlPoint1: CGPointMake(230.73, 135.89), controlPoint2: CGPointMake(230.53, 138.27))
        ePath.addLineToPoint(CGPointMake(255.47, 141.44))
        ePath.addCurveToPoint(CGPointMake(261.43, 138.76), controlPoint1: CGPointMake(257.85, 141.44), controlPoint2: CGPointMake(259.84, 140.55))
        ePath.addLineToPoint(CGPointMake(261.43, 138.76))
        ePath.closePath()
        ePath.miterLimit = 4;

        ePath.usesEvenOddFillRule = true;

        colorActive.setFill()
        ePath.fill()


        //// Fill-1 Drawing
        var fill1Path = UIBezierPath()
        fill1Path.moveToPoint(CGPointMake(55.33, 294.78))
        fill1Path.addLineToPoint(CGPointMake(68.22, 267.48))
        fill1Path.addLineToPoint(CGPointMake(70.08, 267.88))
        fill1Path.addLineToPoint(CGPointMake(75.43, 286.76))
        fill1Path.addLineToPoint(CGPointMake(93.33, 278.86))
        fill1Path.addLineToPoint(CGPointMake(94.82, 280.04))
        fill1Path.addLineToPoint(CGPointMake(81.93, 307.34))
        fill1Path.addLineToPoint(CGPointMake(75.59, 304.34))
        fill1Path.addLineToPoint(CGPointMake(81.8, 291.2))
        fill1Path.addLineToPoint(CGPointMake(71.21, 296.19))
        fill1Path.addLineToPoint(CGPointMake(70.79, 295.99))
        fill1Path.addLineToPoint(CGPointMake(67.82, 284.84))
        fill1Path.addLineToPoint(CGPointMake(61.71, 297.79))
        fill1Path.addLineToPoint(CGPointMake(55.33, 294.78))
        fill1Path.closePath()
        fill1Path.miterLimit = 4;

        fill1Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill1Path.fill()


        //// Fill-2 Drawing
        var fill2Path = UIBezierPath()
        fill2Path.moveToPoint(CGPointMake(95.84, 311.94))
        fill2Path.addLineToPoint(CGPointMake(115.44, 284.7))
        fill2Path.addLineToPoint(CGPointMake(117.89, 285.18))
        fill2Path.addLineToPoint(CGPointMake(125.87, 317.71))
        fill2Path.addLineToPoint(CGPointMake(118.14, 316.23))
        fill2Path.addLineToPoint(CGPointMake(117.19, 312.32))
        fill2Path.addLineToPoint(CGPointMake(105.99, 310.17))
        fill2Path.addLineToPoint(CGPointMake(103.66, 313.44))
        fill2Path.addLineToPoint(CGPointMake(95.84, 311.94))
        fill2Path.addLineToPoint(CGPointMake(95.84, 311.94))
        fill2Path.closePath()
        fill2Path.moveToPoint(CGPointMake(109.59, 304.91))
        fill2Path.addLineToPoint(CGPointMake(115.75, 306.09))
        fill2Path.addLineToPoint(CGPointMake(114.07, 298.23))
        fill2Path.addLineToPoint(CGPointMake(109.59, 304.91))
        fill2Path.addLineToPoint(CGPointMake(109.59, 304.91))
        fill2Path.closePath()
        fill2Path.miterLimit = 4;

        fill2Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill2Path.fill()


        //// Fill-3 Drawing
        var fill3Path = UIBezierPath()
        fill3Path.moveToPoint(CGPointMake(156.5, 305.88))
        fill3Path.addLineToPoint(CGPointMake(164.08, 317.46))
        fill3Path.addLineToPoint(CGPointMake(155.48, 317.75))
        fill3Path.addLineToPoint(CGPointMake(149.69, 308.14))
        fill3Path.addCurveToPoint(CGPointMake(146.47, 308.33), controlPoint1: CGPointMake(148.66, 308.26), controlPoint2: CGPointMake(147.63, 308.29))
        fill3Path.addLineToPoint(CGPointMake(146.8, 318.05))
        fill3Path.addLineToPoint(CGPointMake(139.71, 318.29))
        fill3Path.addLineToPoint(CGPointMake(138.7, 288.42))
        fill3Path.addCurveToPoint(CGPointMake(160.99, 297.39), controlPoint1: CGPointMake(153.65, 285.33), controlPoint2: CGPointMake(160.73, 289.69))
        fill3Path.addCurveToPoint(CGPointMake(156.5, 305.88), controlPoint1: CGPointMake(161.11, 301.21), controlPoint2: CGPointMake(158.82, 304.43))
        fill3Path.addLineToPoint(CGPointMake(156.5, 305.88))
        fill3Path.closePath()
        fill3Path.moveToPoint(CGPointMake(146.26, 302.19))
        fill3Path.addCurveToPoint(CGPointMake(153.68, 297.51), controlPoint1: CGPointMake(151.91, 302.43), controlPoint2: CGPointMake(153.78, 300.47))
        fill3Path.addCurveToPoint(CGPointMake(145.99, 294.07), controlPoint1: CGPointMake(153.59, 294.93), controlPoint2: CGPointMake(151.08, 293.16))
        fill3Path.addLineToPoint(CGPointMake(146.26, 302.19))
        fill3Path.addLineToPoint(CGPointMake(146.26, 302.19))
        fill3Path.closePath()
        fill3Path.miterLimit = 4;

        fill3Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill3Path.fill()


        //// Fill-4 Drawing
        var fill4Path = UIBezierPath()
        fill4Path.moveToPoint(CGPointMake(191.46, 299.56))
        fill4Path.addLineToPoint(CGPointMake(201.32, 309.26))
        fill4Path.addLineToPoint(CGPointMake(192.99, 311.37))
        fill4Path.addLineToPoint(CGPointMake(185.29, 303.2))
        fill4Path.addCurveToPoint(CGPointMake(182.19, 304.08), controlPoint1: CGPointMake(184.31, 303.54), controlPoint2: CGPointMake(183.31, 303.79))
        fill4Path.addLineToPoint(CGPointMake(184.57, 313.5))
        fill4Path.addLineToPoint(CGPointMake(177.69, 315.24))
        fill4Path.addLineToPoint(CGPointMake(170.36, 286.27))
        fill4Path.addCurveToPoint(CGPointMake(194.04, 290.3), controlPoint1: CGPointMake(184.32, 280.08), controlPoint2: CGPointMake(192.16, 282.84))
        fill4Path.addCurveToPoint(CGPointMake(191.46, 299.56), controlPoint1: CGPointMake(194.98, 294.01), controlPoint2: CGPointMake(193.42, 297.65))
        fill4Path.addLineToPoint(CGPointMake(191.46, 299.56))
        fill4Path.closePath()
        fill4Path.moveToPoint(CGPointMake(180.68, 298.12))
        fill4Path.addCurveToPoint(CGPointMake(186.93, 291.97), controlPoint1: CGPointMake(186.24, 297.15), controlPoint2: CGPointMake(187.66, 294.85))
        fill4Path.addCurveToPoint(CGPointMake(178.69, 290.24), controlPoint1: CGPointMake(186.3, 289.47), controlPoint2: CGPointMake(183.47, 288.28))
        fill4Path.addLineToPoint(CGPointMake(180.68, 298.12))
        fill4Path.addLineToPoint(CGPointMake(180.68, 298.12))
        fill4Path.closePath()
        fill4Path.miterLimit = 4;

        fill4Path.usesEvenOddFillRule = true;

        colorActive.setFill()
        fill4Path.fill()


        //// Fill- Drawing
        var fillPath = UIBezierPath()
        fillPath.moveToPoint(CGPointMake(223.05, 266.02))
        fillPath.addLineToPoint(CGPointMake(221.63, 287.48))
        fillPath.addLineToPoint(CGPointMake(226.81, 297.87))
        fillPath.addLineToPoint(CGPointMake(220.41, 301.05))
        fillPath.addLineToPoint(CGPointMake(215.24, 290.66))
        fillPath.addLineToPoint(CGPointMake(197.26, 278.86))
        fillPath.addLineToPoint(CGPointMake(204.73, 275.14))
        fillPath.addLineToPoint(CGPointMake(215.16, 282.2))
        fillPath.addLineToPoint(CGPointMake(215.82, 269.62))
        fillPath.addLineToPoint(CGPointMake(223.05, 266.02))
        fillPath.closePath()
        fillPath.miterLimit = 4;

        fillPath.usesEvenOddFillRule = true;

        colorActive.setFill()
        fillPath.fill()


        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    public class func drawLighthouse() {

        //// Page-1
        //// Shape Drawing
        var shapePath = UIBezierPath()
        shapePath.moveToPoint(CGPointMake(12.79, 26))
        shapePath.addLineToPoint(CGPointMake(11.44, 26))
        shapePath.addLineToPoint(CGPointMake(10.12, 12.86))
        shapePath.addLineToPoint(CGPointMake(11.67, 12.86))
        shapePath.addCurveToPoint(CGPointMake(12.5, 12.01), controlPoint1: CGPointMake(12.13, 12.86), controlPoint2: CGPointMake(12.5, 12.48))
        shapePath.addCurveToPoint(CGPointMake(11.67, 11.16), controlPoint1: CGPointMake(12.5, 11.54), controlPoint2: CGPointMake(12.13, 11.16))
        shapePath.addLineToPoint(CGPointMake(10.02, 11.16))
        shapePath.addLineToPoint(CGPointMake(10.02, 7.39))
        shapePath.addLineToPoint(CGPointMake(10.02, 6.96))
        shapePath.addCurveToPoint(CGPointMake(10.06, 6.72), controlPoint1: CGPointMake(10.04, 6.88), controlPoint2: CGPointMake(10.06, 6.8))
        shapePath.addCurveToPoint(CGPointMake(7.65, 3.52), controlPoint1: CGPointMake(10.06, 5.19), controlPoint2: CGPointMake(9.03, 3.9))
        shapePath.addLineToPoint(CGPointMake(7.65, 1.55))
        shapePath.addCurveToPoint(CGPointMake(6.82, 0.7), controlPoint1: CGPointMake(7.65, 1.08), controlPoint2: CGPointMake(7.27, 0.7))
        shapePath.addCurveToPoint(CGPointMake(5.98, 1.55), controlPoint1: CGPointMake(6.36, 0.7), controlPoint2: CGPointMake(5.98, 1.08))
        shapePath.addLineToPoint(CGPointMake(5.98, 3.52))
        shapePath.addCurveToPoint(CGPointMake(3.57, 6.72), controlPoint1: CGPointMake(4.6, 3.9), controlPoint2: CGPointMake(3.57, 5.19))
        shapePath.addCurveToPoint(CGPointMake(3.61, 6.96), controlPoint1: CGPointMake(3.57, 6.8), controlPoint2: CGPointMake(3.59, 6.88))
        shapePath.addLineToPoint(CGPointMake(3.61, 7.39))
        shapePath.addLineToPoint(CGPointMake(3.61, 11.16))
        shapePath.addLineToPoint(CGPointMake(1.96, 11.16))
        shapePath.addCurveToPoint(CGPointMake(1.13, 12.01), controlPoint1: CGPointMake(1.5, 11.16), controlPoint2: CGPointMake(1.13, 11.54))
        shapePath.addCurveToPoint(CGPointMake(1.96, 12.86), controlPoint1: CGPointMake(1.13, 12.48), controlPoint2: CGPointMake(1.5, 12.86))
        shapePath.addLineToPoint(CGPointMake(3.52, 12.86))
        shapePath.addLineToPoint(CGPointMake(2.19, 26))
        shapePath.addLineToPoint(CGPointMake(0.84, 26))
        shapePath.addCurveToPoint(CGPointMake(0.01, 26.85), controlPoint1: CGPointMake(0.38, 26), controlPoint2: CGPointMake(0.01, 26.38))
        shapePath.addLineToPoint(CGPointMake(0.01, 29.48))
        shapePath.addCurveToPoint(CGPointMake(0.84, 30.33), controlPoint1: CGPointMake(0.01, 29.95), controlPoint2: CGPointMake(0.38, 30.33))
        shapePath.addCurveToPoint(CGPointMake(1.67, 29.48), controlPoint1: CGPointMake(1.3, 30.33), controlPoint2: CGPointMake(1.67, 29.95))
        shapePath.addLineToPoint(CGPointMake(1.67, 27.7))
        shapePath.addLineToPoint(CGPointMake(11.96, 27.7))
        shapePath.addLineToPoint(CGPointMake(11.96, 29.48))
        shapePath.addCurveToPoint(CGPointMake(12.79, 30.33), controlPoint1: CGPointMake(11.96, 29.95), controlPoint2: CGPointMake(12.33, 30.33))
        shapePath.addCurveToPoint(CGPointMake(13.62, 29.48), controlPoint1: CGPointMake(13.25, 30.33), controlPoint2: CGPointMake(13.62, 29.95))
        shapePath.addLineToPoint(CGPointMake(13.62, 26.85))
        shapePath.addCurveToPoint(CGPointMake(12.79, 26), controlPoint1: CGPointMake(13.62, 26.38), controlPoint2: CGPointMake(13.25, 26))
        shapePath.addLineToPoint(CGPointMake(12.79, 26))
        shapePath.closePath()
        shapePath.moveToPoint(CGPointMake(4.73, 17.37))
        shapePath.addLineToPoint(CGPointMake(8.9, 17.37))
        shapePath.addLineToPoint(CGPointMake(9.31, 21.44))
        shapePath.addLineToPoint(CGPointMake(4.32, 21.44))
        shapePath.addLineToPoint(CGPointMake(4.73, 17.37))
        shapePath.addLineToPoint(CGPointMake(4.73, 17.37))
        shapePath.closePath()
        shapePath.moveToPoint(CGPointMake(8.36, 11.05))
        shapePath.addLineToPoint(CGPointMake(7.65, 11.05))
        shapePath.addLineToPoint(CGPointMake(7.65, 10.19))
        shapePath.addCurveToPoint(CGPointMake(6.82, 9.34), controlPoint1: CGPointMake(7.65, 9.72), controlPoint2: CGPointMake(7.27, 9.34))
        shapePath.addCurveToPoint(CGPointMake(5.99, 10.19), controlPoint1: CGPointMake(6.36, 9.34), controlPoint2: CGPointMake(5.99, 9.72))
        shapePath.addLineToPoint(CGPointMake(5.99, 11.05))
        shapePath.addLineToPoint(CGPointMake(5.27, 11.05))
        shapePath.addLineToPoint(CGPointMake(5.27, 8.24))
        shapePath.addLineToPoint(CGPointMake(8.36, 8.24))
        shapePath.addLineToPoint(CGPointMake(8.36, 11.05))
        shapePath.addLineToPoint(CGPointMake(8.36, 11.05))
        shapePath.closePath()
        shapePath.moveToPoint(CGPointMake(6.82, 5.1))
        shapePath.addCurveToPoint(CGPointMake(8.38, 6.54), controlPoint1: CGPointMake(7.63, 5.1), controlPoint2: CGPointMake(8.29, 5.74))
        shapePath.addLineToPoint(CGPointMake(5.25, 6.54))
        shapePath.addCurveToPoint(CGPointMake(6.82, 5.1), controlPoint1: CGPointMake(5.34, 5.74), controlPoint2: CGPointMake(6, 5.1))
        shapePath.addLineToPoint(CGPointMake(6.82, 5.1))
        shapePath.closePath()
        shapePath.moveToPoint(CGPointMake(8.45, 12.86))
        shapePath.addLineToPoint(CGPointMake(8.73, 15.67))
        shapePath.addLineToPoint(CGPointMake(4.9, 15.67))
        shapePath.addLineToPoint(CGPointMake(5.19, 12.86))
        shapePath.addLineToPoint(CGPointMake(8.45, 12.86))
        shapePath.addLineToPoint(CGPointMake(8.45, 12.86))
        shapePath.closePath()
        shapePath.moveToPoint(CGPointMake(4.15, 23.15))
        shapePath.addLineToPoint(CGPointMake(9.48, 23.15))
        shapePath.addLineToPoint(CGPointMake(9.77, 26))
        shapePath.addLineToPoint(CGPointMake(3.86, 26))
        shapePath.addLineToPoint(CGPointMake(4.15, 23.15))
        shapePath.addLineToPoint(CGPointMake(4.15, 23.15))
        shapePath.closePath()
        shapePath.miterLimit = 4;

        shapePath.usesEvenOddFillRule = true;

        StyleKit.teal.setFill()
        shapePath.fill()
    }

    //// Generated Images

    public class func imageOfKeepChoice(#filled: Bool) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(283, 319), false, 0)
            StyleKit.drawKeepChoice(filled: filled)

        let imageOfKeepChoice = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfKeepChoice
    }

    public class func imageOfSkipChoice(#filled: Bool) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(283, 318), false, 0)
            StyleKit.drawSkipChoice(filled: filled)

        let imageOfSkipChoice = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfSkipChoice
    }

    public class func imageOfMarryChoice(#filled: Bool) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(283, 318), false, 0)
            StyleKit.drawMarryChoice(filled: filled)

        let imageOfMarryChoice = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfMarryChoice
    }

}



extension UIColor {
    func colorWithHue(newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func colorWithSaturation(newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func colorWithBrightness(newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func colorWithAlpha(newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, brightness: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func colorWithHighlight(highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func colorWithShadow(shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
